### ISSUE TITLE
Overwrite an existing ModLoader in a pck file

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#116]
We have to check if we can overwrite an existing ModLoader Instance in a pck file.

So the version for Thunderstore can overwrite a build in one.

**Comment by otDan** [comment]
Currently we cannot run the ModLoader that is outside the projects that embed it as the one that is embedded takes priority when loading.

This is mostly needed to support updating the ModLoader in games that embed it in their projects, independently without the need of constant updates pushed by the game developers.

The version for the steam workshop will have to probably work a bit differently as the packages that are downloaded would not be present in the game directory.

For thunderstore and similar the packages would also be either kept in different directories till launch, so the most appropriate way for this would probably to provide a cli argument to update with a path to the new mod loader version.

**Comment by otDan** [comment]
After further research on this, we pretty much can only do this by modifying the game pck the same way we do for adding the ModLoader in a game that does not include it directly.

I have not found any other solution to this problem as a script that is already present internally will always run first and will never allow an external script with the same name and namespace to be ran.

**Comment by KANAjetzt** [comment]
As @otDan mentioned, the only way to override an existing ModLoader is via a PCK tool like [GodotPckTool](https://github.com/hhyyrylainen/GodotPckTool). With this tool, it's relatively easy to build a patcher to update the ModLoader.

A working example for Brotato is here:
- [KANA-ModLoaderPatcher](https://github.com/BrotatoMods/KANA-ModLoaderPatcher)
- [Steam Workshop Link](https://steamcommunity.com/sharedfiles/filedetails/?id=3025396725)
