### ISSUE TITLE
In editor installScriptExtension

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#12]
![image](https://user-images.githubusercontent.com/41547570/210535318-d6d09755-ff7f-4205-bcc2-9e61634b1c1d.png)

ModMain.gd Script Extension:

```python
func _init(modLoader = ModLoader):
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/singletons/utils.gd")
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/singletons/progress_data.gd")
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/main.gd")
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/ui/menus/run/end_run.gd")
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/ui/menus/shop/[shop.gd](http://shop.gd/)")
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/ui/menus/title_screen/title_screen.gd")
    modLoader.installScriptExtension("res://mods-unpacked/KANA-MultiRes/ui/menus/pages/menu_general_options.gd")
```

shop.gd

```python
class_name Shop
extends Control

signal item_bought(item_data)

export (Array, Resource) var combine_sounds = []
export (Array, Resource) var recycle_sounds = []

var _reroll_price: = 0
var _last_reroll_price: = - 1
var _shop_items: = []
var _go_button_pressed: = false

var _initial_free_rerolls = RunData.effects["free_rerolls"]
var _free_rerolls = _initial_free_rerolls

var _need_to_set_locked: = false

...
```

The issue is the

```python
var _initial_free_rerolls = RunData.effects["free_rerolls"]
```

`RunData` is not initialized when the script extension is called

_Originally posted by @KANAjetzt in https://github.com/GodotModding/mod-loader/issues/3#issuecomment-1370746431_

**Comment by ithinkandicode** [comment]
Discussed on Discord but I'll repeat it here for posterity: The issue is that `RunData.effects` isn't ready yet, so the solution is to wait until it's ready before using `installScriptExtension` on `shop.gd`.

In the example below I'm extending debug_service.gd, because it's the last script to be autoloaded In Brotato, so will cover all use cases for that game. But in KANA's case, they may prefer to extend run_data.gd, since that's what they're actually waiting for.

**ModMain.gd**
```
modLoader.installScriptExtension("Author-ModName/extensions/debug_service.gd")
```

_Author-ModName/extensions_**/debug_service.gd** <-- delayed extender
```
extends "res://singletons/debug_service.gd"

func _ready():
	# ._ready() # don't put this here, debug_service.gd has no _ready func in vanilla Brotato

	# Extends: "res://ui/menus/shop/shop.gd"
	ModLoader.installScriptExtension(ModLoader.UNPACKED_DIR + "Author-ModName/extensions/ui/menus/shop/shop.gd")
	print("TEST1=OK: res://singletons/debug_service.gd")
```

_Author-ModName/extensions_**/ui/menus/shop/shop.gd** <-- desired target file
```
extends "res://ui/menus/shop/shop.gd"

func _ready():
	._ready()
	print("TEST2=OK: res://ui/menus/shop/shop.gd")

# Set the reroll button cost to 9999 (takes effect after the first reroll)
func set_reroll_button_price()->void:
	_reroll_button.init(9999)

# Log when an item is purchased
func on_shop_item_bought(shop_item:ShopItem)->void:
	.on_shop_item_bought(shop_item)
	print(str("BOUGHT_ITEM: ", shop_item))
```

**Comment by KANAjetzt** [comment]
There is definitely some inconsistency between making mods work in editor vs. in the exported game.
In my experience it worked in the exported game when it worked in the editor.

The `installScriptExtension` and `saveScene` methods work in the editor 👍

So I will close this.
