### ISSUE TITLE
Optional Dependencies

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#122]
Make it possible to mark a mod as optional dependency.

- [ ] loop through optional_dependencies
- [ ] check if mod_id exists
- [ ] if so increase importance score by 1

**Comment by KANAjetzt** [comment]
From the Space Potatoes Discord
> damzo — Today at 12:35
i think with this utility mod it would be better to have ContentLoader alongside but i'm not too sure how to go about it, since it's not exactly required either. just recommended

**Comment by ithinkandicode** [comment]
It sounds like the way to implement this is with a manifest `extra.godot` key that has no functionality, but only exists as a point of reference, either to other modders or as data that a mod/game can use in-game. Would that be correct?

**Comment by KANAjetzt** [comment]
I think if the optional dependency mod is installed, the dependency should load before the depending mod.
So we still check if the dependency exists, we just don't prevent the mod from loading if the dependency is missing.

**Comment by KANAjetzt** [comment]
closed by #188
