### ISSUE TITLE
Update docs for latest release (5.0.1)

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#126]
It looks like there's a lot of new stuff in the latest release that's not documented.

https://github.com/GodotModding/godot-mod-loader/releases/tag/v5.0.1

- [x] New CLI args @KANAjetzt 
  - [x] `--only-setup` 
  #94 
  - [x] `--setup-create-override-cfg` 
  #99 
- [x] New auto setup process @KANAjetzt @Qubus0 
#75
#89
#94 
#99 
#105
#110 
- [x] overwrites.gd  @KANAjetzt 
#74 
- [x] overrides.cfg @Qubus0 
#75 

I haven't worked on these features so I think they might need to be added by the person who worked on them

**Edit by @KANAjetzt*
*Added @*
**Edit2 by @KANAjetzt*
*Added PRs*

**Comment by ithinkandicode** [comment]
If there's docs that are needed for something you guys have added but aren't 100% confident with writing docs I'm happy to edit and expand on any initial content you write :)

**Comment by ithinkandicode** [comment]
Also, it might be a good idea to add docs for contributing to ModLoader. In particular, how to add new classes to the auto install script.

**Comment by KANAjetzt** [comment]
v5.0.0 is missing on - [Breaking-Changes](https://github.com/GodotModding/godot-mod-loader/wiki/Breaking-Changes)

**Comment by KANAjetzt** [comment]
I think the validation implemented by #71 ?

**Comment by KANAjetzt** [comment]
Just checked - from Discord:

>Darkly77 — 16/02/2023 09:38
What about #91? It's the dependency validation. If a mod on 4.1 has an invalid dependency, it will work, but now the mod won't load

**Comment by ithinkandicode** [comment]
Thanks @KANAjetzt , I've updated the [Breaking Changes](https://github.com/GodotModding/godot-mod-loader/wiki/Breaking-Changes) page on the wiki.

For the auto install docs, @Qubus0 started writing some for PR #33, and I added them to the wiki for safe keeping [here](https://github.com/GodotModding/godot-mod-loader/wiki/@TEMP:-PR33).

**Comment by KANAjetzt** [comment]
I added a new page, "Mod Loader Setup." Feel free to move things around.

https://github.com/GodotModding/godot-mod-loader/wiki/Mod-Loader-Setup

**Comment by KANAjetzt** [comment]
I added the *Overwriting Game Resources* page
https://github.com/GodotModding/godot-mod-loader/wiki/Overwriting-Game-Resources

**Comment by KANAjetzt** [comment]
I don't think we need specific docs fot the *overrides.cfg*?

**Comment by Qubus0** [comment]
no, it can just be part of the setup. since the flags there are already mentioned, we can just add maybe one additional sentence to use that if the pck embedded or optionally if they don't want to modify the exe and don't use mods that change autoloads

**Comment by Qubus0** [comment]
didn't realize there was still something left by me. updated it, I think we're good for 5.x
