### ISSUE TITLE
Directory for resource classes?

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#144]
Should we move the custom resource classes to their own directory? Eg. `mod_loader/classes`. It would contain:

- mod_data
- mod_manifest
- script_extension_data

I think it would clean up the root mod_loader directory a bit and help newcomers understand what each file is doing

**Comment by KANAjetzt** [comment]
A bit unrelated, but we can move *mod_loader_setup.gd* and the *vendor* directory to `mod_loader/setup` as well.

**Comment by Qubus0** [comment]
Sure, better structure is always good

**Comment by ithinkandicode** [comment]
- Closed by:
 #150
