### ISSUE TITLE
Config JSON

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#15]
*(this is mostly copied from [Discord](https://discord.com/channels/1028191864966361178/1060702898364891326/1060702978106998857))*

It would be cool to have a JSON config loader. Eg. my DebugLoader mod already [uses](https://github.com/BrotatoMods/Brotato-DebugLoader/blob/main/debug/debug_loader.gd) a config JSON, and WikiTools has [hardcoded settings](https://github.com/BrotatoMods/Brotato-WikiTools/blob/main/wiki_tools.gd) that I need to replace with JSON-sourced settings instead. So it would be great if we had a standardised system for handling config files, that passed loaded data to the mods when they init. 

I'm thinking the config implementation could be this: 

- Each mod can potentially have its own config file, in a folder called config, with the filename matching the mod ID. 
    - Eg for Invasion, its config file would be here: `res://config/Darkly77-Invasion.json`
- We can store the settings in a variable on modloader, eg `ModLoader.configs["Darkly77-Invasion"]`
    - That way we can pull the settings from the file (if it exists) by only knowing the mod_id, which we'll know before we run `func _init_mod(mod)` -- which means that, when the mod's `_init` fires, that mod can access its config data.
- We can also add a simple utility func to get settings from a mod's own JSON

**Example code for the setting utility:**

```
func get_setting(mod_name:String, setting_name:String):
    return configs[mod_name][setting_name]
```

**Example JSON:**

```
{
	"enable_potatoes": {
		"description": "Adds more potatoes",
		"type": "bool",
		"default": false,
		"current_value": true
	}
}
```

**Misc Ideas:**

- Include a `load_from` option (string), which is a path to a different config JSON file. I did this in [DebugLoader](https://github.com/BrotatoMods/Brotato-DebugLoader), it lets you override the settings with settings from a different file (non-recursive ofc). This lets you have multiple config files you can easily swap out, depending on the situation
- Include a `debug_log` option (bool). This can be checked by `mod_log`, by matching the `log_name` against the mod's own debug_log option. It would let you selectively enable verbose logs for a specific mod. Could also be called `verbose_log`.

**Comment by Qubus0** [comment]
sounds like a good opportunity to use a custom resource to keep everything editable within Godot

**Comment by Qubus0** [comment]
all good points. if we go for a mod manager user interface we could still go for resources to integrate with it directly. json would still work for that as well though
