### ISSUE TITLE
Splitting up long files (utils/core)

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#153]
| Done | Dir | File | Class Name | Notes |
| --- | --- | --- | --- | ---
| ✅ | `api` | **log.gd** | ModLoaderLog | done in #205 |
|✅| `api` | **mod.gd** | ModLoaderMod | All helper functions used by mod devs - #208 `ModLoader` ->  `ModLoaderMod` |
| ✅ | `api` | **config.gd** | ModLoaderConfig | done in #157 |
| ✅ | `api` | **deprecated.gd** | ModLoaderDeprecated |done in #156 |
| ✅ | `internal` | **cli.gd** | _ModLoaderCLI | #226 |
| ✅ | `internal` | **path.gd** | _ModLoaderPath | #226 |
| ✅ | `internal` | **file.gd** | _ModLoaderFile | Including the saving funcs from [#143](https://github.com/GodotModding/godot-mod-loader/pull/143). Maybe JSON funcs too? - done in #226 |
| ✅ | `internal` | **dependencies.gd** | _ModLoaderDependencies | done in #222  |
| ✅  | `internal` | **script_extension.gd** | _ModLoaderScriptExtension | done in #225 |
| ✅ | `internal` | **godot.gd** | _ModLoaderGodot | Eg. `check_autoload_position()` - done in #172 |
| ✅ |  `internal/third_party` |**steam.gd** | _ModLoaderSteam | See related chat in [#148](https://github.com/GodotModding/godot-mod-loader/pull/148), [here](https://github.com/GodotModding/godot-mod-loader/pull/148#discussion_r1119485922) - done in #158 |

### Breaking Changes & Deprecation

Ofc, if we moved the logger funcs then every currently published Brotato mod would break. But we could handle this with a deprecation notice, which can be handled with a new func and that triggers a fatal error in the editor. I've explained how this could work in more detail in #154:

- #154

**Comment by ithinkandicode** [comment]
Additionally, perhaps it would be a good idea to also split up mod_loader.gd? Especially the public API methods.

Here's a table with my notes on class names and grouping (all applies to _mod_loader.gd_ except `ModLoaderLog`):

| Class | Notes |
| --- | --- |
| `ModLoaderCore` | Private methods |
| `ModLoaderAPI` | Public methods |
| `ModLoaderConfig` | Config JSON |
| `ModLoaderOptions` | ML Options (PR #145) |
| `ModLoaderData` | Store for the local vars from _mod_loader.gd_ (eg. `os_mods_path_override`). |
| `ModLoaderLog` | Probably deserves its own class, separate from other utils, as it's used so often |

Using `ModLoaderData` would fix an issue where currently, if you run a func from _mod_loader_utils.gd_ while in ModLoader's `_init()`, there's no way to access local vars from _mod_loader.gd_ -- or maybe there is, but it's not obvious how.

Again, this would be completely breaking for a lot of mods, but we can take the deprecation approach mentioned in the original post above ("Breaking Changes").

**Comment by Qubus0** [comment]
I largely agree. Those are some good splits. A few things:
We should keep away from misc and just keep one generic `ModLoaderUtils`.
Third party should not be lumped together, but we can put it in a separate directory `/third_party_integration`. `ModLoaderUtilsSteamWorkshop`, `ModLoaderUtilsThunderstore`. These names are getting very long though.
Splitting those also allows us to use the `Steam` singleton from GodotSteam, since it won't break if it is not available if the file is never parsed.

Splitting the ModLoader is another thing. If we use `ModLoaderMod` (which I would love) we might also have to use a second autoload. One more step in the setup process.

**Comment by ithinkandicode** [comment]
For the utils classes, would it be better to get rid of the Utils prefix? That would make them a bit shorter, so faster to type. Eg:

- `ModLoaderCLI`
- `ModLoaderFile`
- `ModLoaderSteamWorkshop`

How come `ModLoaderMod` would need to be another autoload?

**Comment by Qubus0** [comment]
Shorter seems fine to me.
If we want to provide access to `ModLoaderMod` like `ModLoader` like we do now, it has to be an autoload.
I did just check though, and we can just make every helper method static by just using `ModLoader.*`.. For example using `ModLoader._saved_objects.append(packed_scene)` in `save_scene` makes it "static"
So, a global class also works

**Comment by ithinkandicode** [comment]
I think that we should publish a release before we start work on a large refactor like this. We're going to lose a lot of commit history by moving things around, so it would be really good to have a point in time (ie., a release tag) that we can refer back to if we want to see the pre-refactor history.

**Comment by KANAjetzt** [comment]
Sorry, I'm late to the party.
What about using ModLoader and ModLoaderUtils as index files?
And just link from there to the actual Class methods?
No breaking changes and keeps the main files somewhat clean.

**Comment by KANAjetzt** [comment]
- [ ] Rename `save_scene()`
> [Qubus0](https://github.com/Qubus0) [yesterday](https://github.com/GodotModding/godot-mod-loader/pull/208#discussion_r1155387838) while we are at moving this here anyway, why don't we rename it as well? save_scene is way too generic. at least save_modified_scene, but that is still a bit unclear... take_over_scene?

- [ ] Move other local vars to `ModLoaderStore`
>[ithinkandicode](https://github.com/ithinkandicode) [17 hours ago](https://github.com/GodotModding/godot-mod-loader/pull/208#discussion_r1156228700) [...] Maybe it would be good to move the other local vars from ModLoader to ModLoaderStore, [...]

**Comment by KANAjetzt** [comment]
Should we move these functions, currently in *mod_loader.gd*, as follows:

- **`_ModLoaderScriptExtension`**
   - `_reset_mods()`
   - `_reload_mods()`
- **`_ModLoaderGodot`**
   - `_check_autoload_positions()`
- **`_ModLoaderSteam`**
   - `_load_steam_workshop_zips()`
- **`_ModLoaderFile`**
   - `_load_mod_zips()`
   - `_load_zips_in_folder(folder_path: String)`
- **`ModLoaderConfig`**
   - `_load_mod_configs()`

**Comment by Qubus0** [comment]
- `_ModLoaderScriptExtension` no. Unless we move all other script extension methods with it.. but to me it seems like ModLoader is the correct class for the job
- `_ModLoaderGodot` no, i'd rather rename `_get_autoload_array` -> `get_autoload_array`, since the class is already internal and the methods are only used outside this class (not private)
- `_ModLoaderSteam` yes.also keep the _ since it's internal but in a public class
- `_ModLoaderFile` sure, but remove the _
- `ModLoaderConfig` yes, keep the _

**Comment by ithinkandicode** [comment]
Closed by:

- #156
- #157
- #158
- #172
- #205
- #208
- #222
- #225

**Comment by KANAjetzt** [comment]
Let's keep this issue open until we are satisfied with the location of each file and until the comment from above regarding the functions in *mod_loader.gd* has been addressed.

**Comment by KANAjetzt** [comment]
closed by *see https://github.com/GodotModding/godot-mod-loader/issues/153#issuecomment-1526460284
