### ISSUE TITLE
save logs up until limit before overriding the files like Godot does it

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#16]
to prevent logs being overridden immediately, I propose that we keep 4 (or what is set in ProjectSettings `logging/file_logging/max_log_files`) older logs, with the time they were created in the name

**Comment by Qubus0** [comment]
https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/core/io/logger.cpp#L151

**Comment by KANAjetzt** [comment]
closed by #100
