### ISSUE TITLE
Discussion: String Standards

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#166]
My feelings:
prefer double quotes over single quotes: `"string"`, not `'string'`
prefer quote escaping over single quotes : `"\"hello\" world"`, not `'"hello" world'` (see comment below)
~~prefer single quotes around strings over quote escaping: `'"hello" world'`, not `"\"hello\" world"`~~

prefer format strings over string concatenation and `str()`: `"hello %s!" % place`, not `"hello " + place + "!"`, not `str("hello", place)`
except for very simple cases/single concatenation: `"hello " + place`, not `"hello %s" % place`

split long strings into shorter ones with string concatenation `"" + "" + ...`, not `str("", "", ...)`
```gdscript
print(
   "pretend that this" +
   "is a really long" +
   "message"
)
```

**Comment by ithinkandicode** [comment]
I agree with everything here. 

Perhaps it would be good to create a new wiki page called Contributing, where we outline the standards we'd like everyone to follow.

**Comment by Qubus0** [comment]
Typically that is done in CONTRIBUTING.md

**Comment by KANAjetzt** [comment]
closed by https://github.com/GodotModding/godot-mod-loader/pull/229
