### ISSUE TITLE
Move Config JSON files to user folder

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#167]
Should configs save to `user://configs`, instead of `res://configs`?

I think saving to the user folder is probably better, because:

- It keeps the game directory clean. 
- It makes it less obvious where the data is held, which should make it less likely that a player will try to modify that data.

**Comment by KANAjetzt** [comment]
+1 for `user://configs`

**Comment by ithinkandicode** [comment]
I've renamed this issue as we've agreed that this should be done.

**Comment by ithinkandicode** [comment]
Closed by #199
