### ISSUE TITLE
Expand configs: Add type, min/max

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#178]
As discussed on the Brotato Discord [here](https://discord.com/channels/630060181086142487/1050470169098588232/1084090938407788544), it would be good to expand the configs to add support for setting types, and perhaps min/max values too.

It adds a bit of extra complexity when parsing the default configs, but I think it's worth it, as it would make implementing a GUI much easier for modders/game developers.

**Example:**

![image](https://user-images.githubusercontent.com/43499897/224485161-f3b9304f-aa19-4b42-aca1-1e89530b9052.png)

**Ideas for options:**

- All: `type`, `default`
- Text: `min_length`, `max_length`, `regex`
- Float/Int: `min_value`, `max_value`, `step` (ie. the amount the value should be incremented by in a mod's GUI)

**Comment by Qubus0** [comment]
So, in essence, you want to use json schema. 
We might be able to use an existing asset for that - 
https://godotengine.org/asset-library/asset/514

https://godotengine.org/asset-library/asset/955

**Comment by KANAjetzt** [comment]
Adding to this refactor:

> Ste — Yesterday at 13:45
we should also provide methods in ModLoaderConfig to get and set values in the config (with a save at the end), just so people don't have to use get_mod_config and do it themselves. then we can private all those methods as well

**Comment by KANAjetzt** [comment]
closed by https://github.com/GodotModding/godot-mod-loader/pull/237
