### ISSUE TITLE
Texture pack /Asset overwrite support

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#179]

**Comment by KANAjetzt** [comment]
For really basic asset overwrites we have 
- #74 

In case of a texture, the current solution requires to match the base resolution 1 : 1.

**Comment by Qubus0** [comment]
Oh yeah totally missed that. A texture pack in that case would just be a mod with an overwrites file and every asset creating an overwrite. 
I wonder if we could also take every asset in the overwrites/ directory and do that. but then we would have to use load instead of preload and there could be an issue with walking the files when they are packed. anyway, I think this can be closed
