### ISSUE TITLE
Versions for dependencies

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#18]
> Darkly77 — Today at 04:39
> Should we start using versions for dependencies? Eg.
> ```
> "dependencies": [
>     {
>         "name": "Dami-ContentLoader",
>         "version": "2.0.0"
>     },
>     {
>         "name": "Darkly77-BFX",
>         "version": "1.0.0"
>     }
> ],
> ```
>  
> Image
> We'd need to use the semver compare approach I mentioned in this issue:
> https://github.com/GodotModding/godot-mod-loader/issues/13
> Only issue is, all ModLoader mods would have to use semver -- ie x.y.z ( major.minor.patch) -- for it to work correctly
> which might be too strict
> though we could probably account for major.minor, as the .patch version in that case can be presumed to be .0 
> same with minor version actually

**Comment by ithinkandicode** [comment]
I'm gonna close this. The dependency checks we have now are fine, and I think implementing this adds a fair bit of complexity that can be better handled by managers like Thunderstore.
