### ISSUE TITLE
Update the readme to contain a bit more info

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#180]
- [x] The Godot version needs to be included (and short info that it hasn’t been ported yet due to missing demand). 
- [x] A link for more info to the wiki main page mentioning that implementation and other docs can be found there. 
- [x] Better explanations/one liners for the existing links.
- [x] Direct link to the “adding to a godot project” page.
- [x] Short explanation that the latest version resides on the development branch.

I’ve been sharing the loader around in the godot discord and multiple people couldn’t find info that we did have
if you have any more, add them here
some things should just go into the wiki, keep that in mind

**Comment by otDan** [comment]
Add compatibility list so Windows, MacOS, Linux, Android, iOS
