### ISSUE TITLE
v6.0.0 - Roadmap

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#181]
- [x] **Bug Fixes**
   - [x] #239
   - [x] #253
   - [x] #262
- [x] **User Profiles**
   - [x] #109 
   - [x] #247
- [x] **Mod API**
   - [x] #219 
   - [x] #221
- [x] **Mod Config**
   - [x] #178 
   - [x] #167 
   - [x] #243
- [x] **Validation**
   - [x] #173
   - [x] #169
   - [x] #186
   - [x] #187 
   - [x] #190
   - [x] #192
   - [x] #242
- [x] **Logging**
   - [x] #140 
   - [x] #141 
   - [x] #263
- [x] **Dependencies**
   - [x] #122 
   - [x] #114 
   - [x] #111
- [x] **Setup**
   - [x] #200 
   - [x] #257 
- [x] **Structure**
   - [x] #165 
   - [x] #153  
   - [x] #245

**Comment by ithinkandicode** [comment]
Note: I've created a label called [breaking](https://github.com/GodotModding/godot-mod-loader/labels/breaking) to help us write the _Breaking Changes_ docs in the next PR.
