### ISSUE TITLE
`_remove_extension` - "A void function cannot return a value"

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#206]
The func `_remove_extension` currently returns `null`, but the func definition says it should return void. This results in an error, because `null` is a return value.

![image](https://user-images.githubusercontent.com/43499897/229291820-5d6ddee7-c873-49a5-888f-601aafb7df85.png)

**Comment by ithinkandicode** [comment]
This will be closed by #206

**Comment by KANAjetzt** [comment]
closed by #203
