### ISSUE TITLE
Different log levels for mod_log

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#21]
> Ste — Today at 16:23
> should we have different logs levels for mod_log? INFO, WARNING, ERROR and just add those at the front of the line? would make reading the logs easier if you use a highlighter

Something like:

`11.1.2023 - 08:28:20   ModLoader-INFO: Initializing -> Cube-HarvestCalc`

**Comment by Qubus0** [comment]
What do you think about different verbosity levels for the logging? `ERROR, WARNING, INFO, DEBUG`, where error is always logged and the others only if their level or a higher one is set as command line option `none, -v, -vv, -vvv`. or as longer flags `--log-warning,--log-info, --log-debug`
In editor I would always assume log debug, though that can fill the output really quickly with how much `dev_log` logs right now

**Comment by Qubus0** [comment]
on another note, I would split it into four methods `log_error` `log_warning` and so on instead of one function with flags

**Comment by KANAjetzt** [comment]
> What do you think about different verbosity levels for the logging? `ERROR, WARNING, INFO, DEBUG`, where error is always logged and the others only if their level or a higher one is set as command line option `none, -v, -vv, -vvv`. or as longer flags `--log-warning,--log-info, --log-debug` In editor I would always assume log debug, though that can fill the output really quickly with how much `dev_log` logs right now

Sound good 👍 
Definitely the longer flags or both.

**Comment by ithinkandicode** [comment]
I think basic logging needs to be enabled by default as it will help us offer support to players. Usually the ones who are having issues will also struggle with things like setting CLI args

**Comment by Qubus0** [comment]
how 'basic' are we talking? Would ERROR level not be enough?
