### ISSUE TITLE
ZIP vs PCK

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#24]
This discussion has come up a few times so I've made a proper issue for it. The loader can support either ZIP or PCK, so it's not a decision we need to make in a hurry, but it would still be good to discuss this to completion.

So: **What are the cases we can make for publishing as ZIPs vs. PCKs?**

---

**ZIP:**

- Universally understood.
- Very easy to make with existing tooling: Zipping is built into Windows, and there's lots of software for other OS's.
- No extra build steps or setup required.
- Easier to extract source code from published mods than don't have a repo, as the code is 1:1. 
  - This makes them easier to maintain -- eg. if the dev leaves the scene or takes a hiatus.
  - And makes them easier to remix -- ie. new modders taking a new spin on a mod. 
  - It also makes creating translations much easier (as GDRETools' CSV extraction doesn't include the keys).
- Can be packaged by any tool, so not tied to Godot.
  - This is good for devs who primarily work in other languages, as they can produce personal packagers particular to their preference (eg. I could easily make a ZIP packager with node.js + Electron because I'm very comfortable with those).
- ZIPs are better for Thunderstore for a few reasons -- see Mythic's feedback [on Discord](https://discord.com/channels/1028191864966361178/1028381928275058838/1063840806466768946).

---

**PCK:**

- As far as I understand things, the sole benefit of publishing PCKs is based on potential options for creating Godot-based tooling:
  - Can be packaged via GDScript, whereas ZIPs can't be. So if we develop tooling to package mods, they'll have to be PCK.
  - Tooling will need docs and an interface that anyone can use, and since it's an extra step it needs to be more convenient than just zipping up a folder.
  - The tool(s) would ideally be easy to update by anyone in the scene, both for maintenance, and to make it easy to expand with ideas from other contributors (it's good to keep in mind that to making mods for games like Brotato doesn't require experience with GUI editing).

---

Based on this, it seems like ZIPs are the most convenient option. 

**What are the other benefits of using PCKs?**

Related: #22

**Comment by KANAjetzt** [comment]
>  PCK versus ZIP pack file formats¶
>  Each format has its upsides and downsides. PCK is the default and recommended format for most use cases, but you may want to use a ZIP archive instead depending on your needs.
>  
>  PCK format:
>  
>  Uncompressed format. Larger file size, but faster to read/write.
>  
>  Not readable and writable using tools normally present on the user's operating system, even though there are third-party tools to extract and create PCK files.
>  
>  ZIP format:
>  
> Compressed format. Smaller file size, but slower to read/write.
> 
> Readable and writable using tools normally present on the user's operating system. This can be useful to make modding easier (see also Exporting packs, patches, and mods).
> _https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html#pck-versus-zip-pack-file-formats_ 

Fro the docs - so basically file size vs. loading speed.

**Comment by KANAjetzt** [comment]
> Can be packaged via GDScript, whereas ZIPs can't be. So if we develop tooling to package mods, they'll have to be PCK.

This can be circumvented by calling an "external" tool via `OS.execute()` to zip something inside a godot plugin.
This is currently used in the [Plugin](https://github.com/GodotModding/godot-mod-tools/tree/main/godot-mod-export-tool-plugin/godot-3)

The downside with that is, if you use a godot 4 .exe, you ship over 60 MB to zip some files.

**Comment by ithinkandicode** [comment]
I'm gonna close this for now to declutter the issues. I think we decided to use ZIP, at least for now. It should help with integrations too so I think we're all good here 🤗
