### ISSUE TITLE
Configs API - Method Suggestions

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#243]
A few suggestions for the configs API (`ModLoaderConfig.*`).

| Method | Notes |
| --- | --- |
| `reset_mod_config_to_default(mod_id)` | Resets settings to their defaults, and saves to the user config JSON. |
| `save_mod_config_by_mod_id(mod_id)` | Wrapper for `save_mod_config_dictionary`, but doesn't require passing a data object. This would be the main intended method for saving config settings. Alternatively, the `data` arg could be set to default to `{}`, which would have the same effect. |
| `get_mod_configs_path()` | Wrapper for `_ModLoaderPath.get_path_to_configs`. Could be used to run an OS command to open the user configs folder. Not needed if we expose ModLoaderPath as a public class. |

**Comment by KANAjetzt** [comment]
- **reset_mod_config_to_default(mod_id)**
With the new setup, the default config is immutable, and the user can always switch back to it.

- **save_mod_config_by_mod_id(mod_id)**
The `update_config(config: ModConfig)` method takes an updated mod config, validates it, and saves it to the file system. The `ModConfig` class stores the `mod_id` and the path to the config file.

- **get_mod_configs_path()**
I hope that with the current system, the user is not required to access the config path. However, I'll keep that in mind, and it can be added later if there is a request.
