### ISSUE TITLE
Use mods workshop id when handling steam workshop mods

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#280]
to improve the connection with the steam workshop and games, use the steam workshop id either alongside the current id or instead of it. the only way i see to get the workshop id is from the directory it is downloaded in, but there might be better ones, especially if we implement methods to download mods through the modloader

https://godotsteam.com/tutorials/workshop/

**Comment by otDan** [comment]
I do not think we want to embed godot steam functions into the mod loader, how would you handle it?

**Comment by KANAjetzt** [comment]
We don't have to embed GodotSteam functions only store the workshop id right?

**Comment by KANAjetzt** [comment]
Is it enough to store the workshop_id in ModData?
With #298 we can get it from the zip path.

**Comment by KANAjetzt** [comment]
If `_ModLoaderSteam` were to be made "public," I think adding a `get_workshop_id(mod_id: String)` method would be nice. However, I think it's fine to add it to `ModLoaderMod` even if it's useless for non-Steam games.

**Comment by KANAjetzt** [comment]
@Qubus0 Can we close this? 

Maybe we can think about adding APIs for uploading to the workshop, so the uploader can be integrated into the game.

**Comment by Qubus0** [comment]
yep seems fine to close, now that we have the id in the manifest
