### ISSUE TITLE
Add Allowlist/Denylist instead of just the "Ignored Mod Names In Log"

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#282]
This will allow to only show specific `mod_ids` in the logs.
Handy for mod developers who want to fix their deprecation warnings.

**Comment by KANAjetzt** [comment]
> Handy for mod developers who want to fix their deprecation warnings.

I just realized that we need a different solution for this use case. Setting the `mod_id` of your own mod on the Allowlist will also ignore all `ModLoader:Deprecated` logs. Similarly, if you set `ModLoader:Deprecated` on the Allowlist, you will receive all deprecation warnings.

**Comment by ithinkandicode** [comment]
If it's any help, I don't think the deprecation issues are gonna be around for long. All the Brotato dependencies that I've seen are either for my utility mods, or for dami's mod options. 

I plan to release patches as soon as the public v1 of Brotato is released, and dami's mod will need an update anyway, to use the juicy new config stuff we've added.

**Comment by KANAjetzt** [comment]
Agreed. Let's wait and see if there is a demand for this feature. For now, I will close this issue.
