### ISSUE TITLE
Require `namespace-modname-version.zip` as naming convention for zip files

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#294]
This is mandatory for implementing #249 ~~and will help fix #288~~. 

Edit1:
#288 has been resolved using a different solution.

**Comment by ithinkandicode** [comment]
As mentioned on Discord today, this would break most of Brotato's mods. I checked the 30 most popular mods and their ZIP filenames, here's the results:

Here's Brotato's 40 most popular mods of all time, and the ZIP filenames they use:
```
2939837463 = AnyWeapon.zip
2965027290 = AutoBattler.zip
2940464308 = betterSaver.zip
2929535073 = Blobfish-Bobby.zip
2937529849 = Chromium-BetterBoxes.zip
2931733857 = Cube-HarvestCalc-v1.1.0.zip
2944608034 = dami-ModOptions-0.3.1.zip
2937202411 = dami-MoreTiers.zip
2944082895 = dami-SoundFixes.zip
2931388001 = Darkly77-BFX-v2.3.1.zip
2931388196 = Darkly77-Brotils-v1.1.0.zip
2931387684 = Darkly77-ContentLoader-v6.2.0.zip
2936604049 = Darkly77-CustomDifficultyModes-v2.0.0.zip
2934217303 = Darkly77-ExpandedChallenges-v1.1.0.zip
2931400839 = Darkly77-Invasion-v0.11.0.zip
2934587689 = Darkly77-LimitProjectiles-v1.0.0.zip
2934796577 = Darkly77-ShowChallengeNames-v1.0.0.zip
2935491189 = Darkly77-ShowModSource-v1.0.2.zip
2934197660 = Darkly77-WiderCharacterSelect-v1.0.0.zip
2944003713 = diversified.zip
2931665537 = Elemento.zip
2943075609 = EndlessOrNot.zip
2932537673 = EviePatamon-Patamods.zip
2937818785 = flabort-GMO-0.2.0.zip
2947760698 = FrakiLoZ-SpellThief-V1.0.1.zip
2934277576 = ImprovedArmorTooltip 1.0.5.zip
2944885435 = KANA-ScrollWithController.zip
2935571472 = kuiwaiwai-MinusTen.zip
2945834067 = Lynkkk-zhiyinMod.zip
2951011475 = Lynkkk-zhiyinModOverPowered.zip
2935226667 = Mortato.zip
2937057646 = otDan-BetterModList-1.4.0.zip
2941387735 = otDan-ItemExplorer-1.4.0.zip
2931146015 = Psina-Extatonion.zip
2961363050 = Retromations-Infinite.zip
2967418648 = ShowEnemyHealth.zip
2964355955 = signalAPI.zip
2950527446 = splitStat.zip
2955534184 = Vleague.zip
2931164804 = yuwuhuaxiang-Jujuwuyu.zip
```

Here's the stats for those ~~40~~ 30 most popular mods. I've excluded my 10 mods so that they don't skew the data:

* 4 mods use `Author-Mod-Version`
* 2 mods use `Author-Mod-vVersion` *(this is what my 10 mods use too)*
* 1 mod uses `Mod{space}Version`
* 12 mods use `Author-Mod`
* 11 mods use `Mod`

**Comment by boardengineer** [comment]
Does this project control the uploader? Could the zips be renamed on submission?

**Comment by KANAjetzt** [comment]
The upload for workshop mods is handled by this tool:
https://github.com/thomasgvd/godot-workshop-utility

The mod loader doesn't really care where the mod is from. It just loads any .zip or .pck file from a specified location.

So all we can do is validate the filename when traversing that mod zip location.

**Comment by ithinkandicode** [comment]
For reference: Here's the ZIP filenames for all 153 mods currently on the Brotato workshop.

[All Brotato Mod ZIP Filenames.txt](https://github.com/GodotModding/godot-mod-loader/files/11858970/All.Brotato.Mod.ZIP.Filenames.txt)

- 8 use `Author-Mod-Version` -- `[A-z0-9]+-[A-z0-9]+-[0-9.]+`
- 17 use `Author-Mod-vVersion` -- `[A-z0-9]+-[A-z0-9]+-v[0-9.]+`
- 128 use something else

**Comment by aesereht** [comment]
about
- 17 use `Author-Mod-vVersion` -- `^[A-z0-9]+-[A-z0-9]+-v[0-9.]+$`

it's actually
- 3 use `Author-Mod-VVersion` -- `^[A-z0-9]+-[A-z0-9]+-V[0-9.]+$`
- 14 use `Author-Mod-vVersion` -- `^[A-z0-9]+-[A-z0-9]+-v[0-9.]+$`
unless used `[vV]`

And would guess if you look in depth to names, there could be more inconsistencies like one author using two different formats
- `yuwuhuaxiang-Jujuwuyu-english_version`
- `yuwuhuaxiang-Jujuwuyu`

**Comment by otDan** [comment]
I wouldn't enforce it on the zip since it's hard to control, also we could only control it in the workshop uploader, it would be better to control the mod folder name under mods-unpacked that way we can verify that, informate the dev and control it also outside of only steam
to retrieve the path to the assets if you wanna depend on the mod we could just provide an easy method that retrieves it from the mod id

**Comment by KANAjetzt** [comment]
I believe we can leave the zip names unvalidated for now and wait for the [ZIPReader](https://docs.godotengine.org/en/stable/classes/class_zipreader.html) in Godot 4.

**Comment by KANAjetzt** [comment]
I'm closing this - since version [6.2.0](https://github.com/GodotModding/godot-mod-loader/releases/tag/v6.0.2), we always unpack mods before we decide whether to initialize them or not. Regarding #249, if the zip is named the same, it will override itself. We can't control which version is picked here. If the zip has a different name, we can now check the version in the manifest and decide based on that which mod to load or not.
