### ISSUE TITLE
Fatal Error in Mod Loader Code

### ISSUE THREAD

**Issue by KirbyKid256** [GodotModding/godot-mod-loader#317]
I've been trying to make a mod for a game using this Mod Loader, and I don't know if anyone has brought this up but the 6.0.2 version of the mod loader causes a fatal crash. Specifically in the mod_loader.gd script with line 339:
`var mod_main_instance: Node = mod_main_script.new(self)`

There should be no arguments in new(). For me at least, this has been causing false fatal errors revolving around the use of deprecated functions and variables when the real fatal error is the use of self (or anything) in new(). So the line should instead be:
`var mod_main_instance: Node = mod_main_script.new()`

**Comment by otDan** [comment]
no the argument is the ModLoader itself as you can see in the code itself, this isn't currently used anywhere since 6.0 moved most stuff out of the main class, but it's still required and you just provide whatever you wanna call the argument like in this example:
```
func _init(modLoader = ModLoader) -> void:
	mod_dir_path = ModLoaderMod.get_unpacked_dir().plus_file(MOD_DIR)

	# Add extensions
	install_script_extensions()
```

**Comment by otDan** [comment]
the wiki also provides you with an example
https://github.com/GodotModding/godot-mod-loader/wiki/Mod-Files#mod_maingd

**Comment by KirbyKid256** [comment]
I've already used that example. And unchanged, I get deprecated messages using it. When follow ALL the depracated message instructions on what to replace and there's nothing to replace, for a split second I get the message in image 1, then it gives me another deprecated message even though I have nothing deprecated in my mod. The deprecated message would be either about the UNPACKED_DIR variable or the mod_data variable
<img width="625" alt="Screenshot 2023-07-02 at 7 58 42 PM copy" src="https://github.com/GodotModding/godot-mod-loader/assets/70983335/782b83bb-c4b1-4550-97ec-f2223c326387">
<img width="714" alt="Screenshot 2023-07-02 at 9 57 47 PM" src="https://github.com/GodotModding/godot-mod-loader/assets/70983335/abf844e5-dd5c-4892-9db9-da0079ec02fa">

**Comment by otDan** [comment]
I am referring to only passing the ModLoader, everything else is deprecated yes, not that
