### ISSUE TITLE
Sandbox/Security for mods

### ISSUE THREAD

**Issue by BraedonWooding** [GodotModding/godot-mod-loader#337]
Is there anything currently done to sandbox the mods loaded?  I had a look through the other issues but couldn't find anything in relation to this.

https://github.com/godotengine/godot-proposals/issues/5010 talks about a sandbox mode for this use-case but I wanted to confirm there wasn't anything special done such as preventing access to OS/IO.

**Comment by Qubus0** [comment]
No. We also can't do much about it. 

If you need strong sadboxing, I would recommend wasm (https://godotengine.org/asset-library/asset/1877) or lua (https://godotengine.org/asset-library/asset/1970) based systems. Alternatively, if your game architecture allows, you could also go down the same route that Luck be a Landlord chose. https://github.com/TrampolineTales/LBAL-Modding-Docs/wiki

All of these modding solutions require you to build a solid api and are way higher effort compared to this mod loader. It always depends on what you need. Hope that helps.
