### ISSUE TITLE
create a wiki and shrink the README.md

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#35]
this will make everything easier to maintain and simplify merges
the readme can link to pages in the wiki instead of containing everything.

**Comment by Qubus0** [comment]
see comment by @ithinkandicode: https://github.com/GodotModding/godot-mod-loader/pull/33#pullrequestreview-1249893772
concerning [this version of the readme](https://github.com/GodotModding/godot-mod-loader/blob/b90ed1d016689ea139da72870f4c393a1a84b8bf/README.md)
and also consider this [version of the readme](https://github.com/GodotModding/godot-mod-loader/blob/8e501b28690dabea9bcef167c8d9069dd95eb9e1/README.md)

**Comment by ithinkandicode** [comment]
done in #37
