### ISSUE TITLE
latest build kinda doesen't work with self-setup guide

### ISSUE THREAD

**Issue by walksanatora** [GodotModding/godot-mod-loader#356]
so I unzipped and made the addons folder but...
```
ERROR: Attempt to open script 'res://addons/mod_loader/mod_loader_setup.gd' resulted in error 'File not found'.
   at: (modules\gdscript\gdscript.cpp:1032)
ERROR: Failed loading resource: res://addons/mod_loader/mod_loader_setup.gd. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core\io\resource_loader.cpp:274)
ERROR: Can't load script: addons/mod_loader/mod_loader_setup.gd
   at: (main\main.cpp:2923)
   ```

**Comment by walksanatora** [comment]
if I list the mod_loader folder it does infact not exist.
```
api/       mod_loader.gdc       mod_loader_store.gdc       options/    setup/
internal/  mod_loader.gd.remap  mod_loader_store.gd.remap  resources/
```

**Comment by KANAjetzt** [comment]
Hi and thanks for reporting.
Can you share some more information? 
What steps did you take, what game do you want to mod, Godot version, OS?

**Comment by walksanatora** [comment]
so I downloaded the latest release from https://github.com/GodotModding/godot-mod-loader/releases/tag/v6.2.0
unzipped `ModLoaderCompiled.zip` next to [WindowKill](https://torcado.itch.io/windowkill) and modified WindowKill's `windowkill-opengl.bat` which launches the game using opengl instead of vulkan
but the ModLoaderCompiled does not have mod_loader_setup.gd
I also tried downloading the Source Code (zip) and unzipping and placing the addons folder in the same spot. but neither worked because `mod_loader_setup.gd` is not in either of them
I am running on linux through wine

**Comment by KANAjetzt** [comment]
Thanks for the details.
The current released versions of the mod loader are for Godot 3.5. WindowKill is created with a custom build of Godot 4.2. The creator of the game released the custom engine build used here:
https://github.com/torcado194/godot/tree/windowkill

There is a post on the Godot Discord Showcase, you can follow that for a bit more information.

Regarding the zip downloading, that's a good point. We should add a zip to the release that can be used for the self-setup.
