### ISSUE TITLE
Add add_child_below_node to `append_node_in_scene`

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#4]
- There is a helper function to add a node to modified scene but you cant define the position of the node

- [ ]  add `add_child_below_node()` to `ModLoader.append_node_in_scene()`

**Comment by ithinkandicode** [comment]
@KANAjetzt is this something you'll be able to implement? I don't know enough about Godot yet to do this

**Comment by KANAjetzt** [comment]
Yep 👍 

I actually do this in multi res right now.

Should be pretty strait forward to implement.

**Comment by ithinkandicode** [comment]
Note: updated the title and initial message to use the func name since the rename --  `append_node_in_scene`

**Comment by KANAjetzt** [comment]
`append_node_in_scene` is barely used on the 3.x side, and in 4.x, we changed the way we modify scenes.
