### ISSUE TITLE
Enable the extending of existing extensions existing in a dependency

### ISSUE THREAD

**Issue by a-usr** [GodotModding/godot-mod-loader#401]
Sometimes users might want to create a libary-like mod that abstracts over the existing modding api of a game or implements a modding api temporarily until the game developer pushes the update containing that api.

 In those cases it would be nice to have the capabilities of extending those apis before the extensions containing those apis are applied, while having the guarantee that the current mod will only successfully load if the dependency is installed.

**Comment by Qubus0** [comment]
Do i understand this layout correctly?
if so, you can use `load_before` (ref [wiki: manifest.json](https://github.com/GodotModding/godot-mod-loader/wiki/Mod-Files#manifestjson)) to force the api to lead after your pre-modifications

⏹ Vanilla

⤴️ Your mod 
- in your control
- `load before: API mod`

⤴️ API mod 
- no control

⤴️ your current mod
- also in your control
- `dependency: API mod`
- or `optional dependency: API mod` if only want to load after but don't rely on it, which does not seem to be the case here

**Comment by KANAjetzt** [comment]
Here are two example library mods. Other mods can just add the mod-ID as a dependency and use the provided methods:
https://github.com/BrotatoMods/Brotato-Brotils
https://github.com/BrotatoMods/Brotato-ContentLoader

I used `load_before` here to extend an existing mod:
https://github.com/BrotatoMods/KANA-ItemExplorerExtension

**Comment by a-usr** [comment]
> you can use load_before (ref [wiki: manifest.json](https://github.com/GodotModding/godot-mod-loader/wiki/Mod-Files#manifestjson)) to force the api to lead after your pre-modifications

To be honest i didnt even notice the `load_before` key, Thank you for pointing me in the right direction!
Also I'd like to suggest adding a wiki entry for that, because this is where I started looking for info (just not in the page for the manifest)
> Here are two example library mods. Other mods can just add the mod-ID as a dependency and use the provided methods:
 [...]
I used load_before here to extend an existing mod:
https://github.com/BrotatoMods/KANA-ItemExplorerExtension

thank you too for the example!
