### ISSUE TITLE
Loading prevention for incompatible game version

### ISSUE THREAD

**Issue by aesereht** [GodotModding/godot-mod-loader#407]
It would be good to consider a method of adding prevention from loading a mod in case of incompability.

There is currently arguments in json manifest schema

```json
	  "compatible_mod_loader_version": "4.0.0",
	  "compatible_game_version": ["4.0.3"],
```
while there is a method for handling mod_loader_version `_handle_compatible_mod_loader_version` there is non for game_version nor game engine

`compatible_game_version` if it's minor changes probably should be implemented by dev directly although there could be added helper method.

The real problem if devs would decide to change engine version as due to syntax changes it would crash the game while trying to load files. So would propose adding `compatible_engine_version`, where engine version could be easily retrieve by `Engine.get_version_info()`

**Comment by KANAjetzt** [comment]
closed by #416
