### ISSUE TITLE
Can't access const attributes of a global class_name when the game is compiled

### ISSUE THREAD

**Issue by lafitteque** [GodotModding/godot-mod-loader#418]
I have Data.gd **inside my mod** containing : 

```
extends Node2D
class_name Data

const my_int : = 1

```

In godot editor, I can use anywhere Data.my_int without ever instantiating any Data object 
When the game is compiled, I can't access Data.my_int.

This means that, with the same .zip, if you run the game in the editor, the mod runs properly but if you run it in the compiled game, it doesn't.

**Comment by KANAjetzt** [comment]
Hi I'm guessing Godot 4, can you share the game you are modding?

**Comment by lafitteque** [comment]
Hi, I'm modding on Dome Keeper in godot 4 as you guessed. 

A way around this issue is to create a scene with a single node with this script and then finding it whenever I need it.

**Comment by KANAjetzt** [comment]
> I have Data.gd inside my mod containing  

Sorry, I misunderstood the issue last time.  
Global class names can't be used in mods. More details about that can be found here:  
https://wiki.godotmodding.com/#/guides/modding/global_classes_and_child_nodes
