### ISSUE TITLE
[4.x] Mod Hooks: Add something to check if the export plugin is used

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#438]
Without that, dynamic hooks will be created on top of those from the export plugin.

**Comment by Qubus0** [comment]
if we disable hook gen completely we can just add an empty file to the export and stop if that is present. 

if we want to do this per-file or allow an override that bypasses the full stop, we could end the files with a comment like `# Mod Loader Hooked`. unless we want to mess with file metadata which might be faster but also more risky with OS differences? would need testing i don't know enough about that

**Comment by KANAjetzt** [comment]
closed by #493
