### ISSUE TITLE
validate mod config json if present during zip peeking

### ISSUE THREAD

**Issue by Qubus0** [GodotModding/godot-mod-loader#444]
methods are already implemented on the resources and just need to be triggered and disable the mods

todo from #416

**Comment by KANAjetzt** [comment]
If I see this right - mod manifest is already loaded and validated here:

https://github.com/GodotModding/godot-mod-loader/blob/3a889664c8557fedb3315076d205a3bf8aab6e8b/addons/mod_loader/mod_loader.gd#L82

**Comment by KANAjetzt** [comment]
Not sure about the profile part?

**Comment by Qubus0** [comment]
right, the manifest is already validated
https://github.com/GodotModding/godot-mod-loader/blob/3a889664c8557fedb3315076d205a3bf8aab6e8b/addons/mod_loader/resources/mod_data.gd#L143-L151

i think i meant config instead of profile.

**Comment by Qubus0** [comment]
maybe the manifest does need additional validation like checking all dependencies are there before loading.

**Comment by KANAjetzt** [comment]
I close this, we have #445 open for mod configs. And for dependency validation we have #454.
