### ISSUE TITLE
Need more info on .import folder

### ISSUE THREAD

**Issue by Squix** [GodotModding/godot-mod-loader#460]
Hi,
thanks for the amazing work here :)

I made a mod for a self-install game (Buckshot Roulette). It loads a custom .png and use it as a sprite for a new node in the game.

It works in the editor. 

It is recognized by the modloader in the patched game when exported as a zip file, however, the png is not loaded and I get this error in *game/logs/godot.log* :

```
USER ERROR: Unable to open file: res://.godot/imported/custom_sprite.png-2e0f6f3d3738adfdc66e85a972c54b8a.s3tc.ctex.
   at: _load_data (scene/resources/texture.cpp:847)
USER ERROR: Failed loading resource: res://.godot/imported/custom_sprite.png-2e0f6f3d3738adfdc66e85a972c54b8a.s3tc.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:273)
USER ERROR: Failed loading resource: res://mods-unpacked/Squix-ModName/custom_sprite.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:273)
```

Here's the zip file hierarchy :
```
ModName-1.0.0.zip
├── .import
│   ├── custom_sprite.png.import
│   └── custom_sprite.png-2e0f6f3d3738adfdc66e85a972c54b8a.s3tc.ctex
└── mods-unpacked
    └── Squix-ModName
        ├── mod_main.gd
        ├── manifest.json
        └── custom_sprite.png
```

And the code loading the custom_sprite.png :
```
const AUTHORNAME_MODNAME_DIR := "Squix-ModName"

var mod_dir_path := ""

func _init() -> void:
	mod_dir_path = ModLoaderMod.get_unpacked_dir() + AUTHORNAME_MODNAME_DIR
	
func _process(delta) -> void:
   ...
   var node : Sprite3D = Sprite3D.new()
   var texture = load(mod_dir_path.path_join("custom_sprite.png"))
   node.texture = texture
   get_tree().get_current_scene().add_child(node)
   ...
```

I tried moving around the custom_sprite.png and custom_sprite.import between the *mods-unpacked/Squix-ModName* and the *.import* folder, but I always have the same error.

The documentation is not enough clear and the modding-example repo is outdated :

- **Which generated files should be placed in .import ?**
- **In the mod code, where my custom .png should be loaded from ? The mods-unpacked/Squix-ModName or .import ?**

Thanks !

**Comment by Qubus0** [comment]
hey there, `.import` has moved to `.godot/imported` in godot 4, that is likely your issue. i've opened a docs issue

and i'd recommend moving this part at least out of process
```gdscript
   var node : Sprite3D = Sprite3D.new()
   var texture = load(mod_dir_path.path_join("custom_sprite.png"))
   node.texture = texture
   get_tree().get_current_scene().add_child(node)
```
unless you want a new one each frame

**Comment by Squix** [comment]
Well, thanks, I renamed .import to .godot/imported in my zip file.

Which files should be in this folder though ? Only the .s3tc.ctex file ? Or the .import one is important too ?

And for your comment on process, some code above ensures this part is only executed once ;)

**Comment by Qubus0** [comment]
you can take a look into your imported folder if you enable showing hidden folder in your file explorer. i think it's only the ctex files.
```
.zip/
└── .godot/
    └── imported/
        └── custom_sprite.png-2e0f6f3d3738adfdc66e85a972c54b8a.s3tc.ctex
```
though i personally just use the [mod tool](https://github.com/GodotModding/godot-mod-tool/tree/4.x) because i can't be bothered

**Comment by Squix** [comment]
Okay, I only see .ctex and .md5 files, so it makes sense.

EDIT : the custom_sprite.import file is mandatory though, and should be next to the custom_sprite.png

Thanks !
