### ISSUE TITLE
Track overwrites

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#79]
Once the basics of #14 are implemented, I would like to see if its fessable to track witch mod is overwriting what resource. To potentially log a warning if 2 mods overwrite the same thing.

To do this with the implementation from #74 the ``overwrites.gd`` or the ``overwrites`` folder has all the information we need to do this. If the mod creator followed the recommendation to mirror the games folder structure inside the ``overwrites`` folder.

So 2 possibilities I can think of:

A) Regex the ``overwrites.gd`` for paths starting with ``res://``
B) Use ``get_flat_view_dict(overwrites_folder)``

Then save the paths to the original resources in mod_data and compare.

**Comment by ithinkandicode** [comment]
For both of these solutions there will be a performance cost involved, and caveats.

- a) We also need to keep in mind that the regex will need to be perfect and would need to account to variation in how people code things.
- b) That would be dependent on modders having a standardised setup, and I've seen first-hand that they sometimes don't, so I don't this this option is viable.

So with just option A available, is the benefit worth the performance cost? And can we ensure that whatever regex we create could handle all user cases?

**Comment by KANAjetzt** [comment]
This has been open for quite some time, and currently, we don't have a need for this functionality, so I will close it for now.
