### ISSUE TITLE
Mod Loader without editing source code

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#8]
> **Ste - *January 3, 2023 11:37 AM***
Hey btw, back to the idea of only needing the modloader and not some edits to the source code (like adding it as auto load): godot can override project settings with a override.cfg placed in the same directory as the exe. One problem being that it completely replaces it and can’t just ‘add to it’.. though there might be a way, since you can save the project settings as a custom file ([https://discord.com/channels/212250894228652034/342056330523049988/873285063805124678](https://discord.com/channels/212250894228652034/342056330523049988/873285063805124678))
> 
> 
> > I can save these config settings very easily using the following:
> > 
> > 
> > ```
> > var path = ProjectSettings.globalize_path(OS.get_executable_path().get_basename() + "override.cfg")
> > ProjectSettings.save_custom(path)
> > ```
> > 
> 
> That means we could possibly run the project once, make it add itself to the auto loads, create the override and close again
> 

> **Ste - *January 3, 2023 11:51 AM***
Adding it as auto load might be a bit annoying though, since it is added as last in the list. So get existing, hold them, remove them, add loader, add them back..
also, save_custom saves all of the settings, which might be bad.. and projects using this mechanic might be affected (though i've never seen a project use that)
>

**Comment by ithinkandicode** [comment]
Closed in #75
