### ISSUE TITLE
Remove the need to add a cmd line arg for run.gd

### ISSUE THREAD

**Issue by ithinkandicode** [GodotModding/godot-mod-loader#9]
Atm there's a requirement with Brotato to launch the game with `--script run.gd`. Can we remove the need for the cmd line arg, and potentially for the [run.gd](https://github.com/GodotModding/mod-loader/blob/main/loader/run.gd) file?

I'm not sure what it does/why it's needed so if anyone can illuminate me I'll be happy to discuss options and workarounds and potentially code a fix.

**Comment by Qubus0** [comment]
we can only have one of the two: 
1. edit the source code wit the mod loader as autoload and recompile (best case scenario: the game developer does that)
2. use a command line flag for a script that injects the modloader as autoload before the game runs

what i'm currently working on will make both cases easier/more convenient to use. Though i'm not sure if that fulfil the conditions to 'solve' this

**Comment by ithinkandicode** [comment]
Resolved in #78
