### ISSUE TITLE
Investigate potential side effects when overwriting resources

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-loader#97]
> Darkly77:
> ~~Another use case for replacements: You could do stuff like make a balance pack for Brotato [...]~~
>
> I've found that replacing files can be a bad idea because it can mess up extended scripts.
>
> I was trying a few things with the file *character_selection.tscn*, and after replacing it I found that the extended scripts for *character_selection.gd* (which is referenced in *character_selection.tscn*) no longer worked. Replacing *.tres* files likely has the same negative effect, where any *.gd* scripts that are referenced in that *.tres* file will ignore their extensions.
>
> This needs further testing though.

_Originally posted by @ithinkandicode in https://github.com/GodotModding/godot-mod-loader/issues/14#issuecomment-1416504321_

**Comment by ithinkandicode** [comment]
Here's how I would test this:

1. Find a scene that has scripts attached to it -- eg. in Brotato, *character_selection.tscn* has *character_selection.gd*
1. Extend that scene's script, adding a `print`
1. Update the scene using `save_scene`
1. Check to see if the first print worked.
1. Extend that scene's script again, adding another `print`
1. Check to see if both prints worked.

I would also use `save_scene` a second time, with more before/after script extension tests.

This will tell us if there are repercussions from using `save_scene`.

*note: I've also edited original message to show the quote*

**Comment by ithinkandicode** [comment]
Seems fine to me, we can re-open if needed
